name: substation_app
description: A new Flutter application.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  firebase_auth: any
  firebase_auth_ui: any
  firebase_core: ^0.5.0
  flutter_spinkit: ^4.1.2+1
  fluttertoast: ^7.1.1
  font_awesome_flutter: ^8.11.0
  google_sign_in: ^4.5.6
  http: ^0.12.2
  intl: ^0.16.1
  path_provider: ^1.6.24
  rflutter_alert: ^1.1.0
  shared_preferences: ^0.5.12+4
  sqflite: ^1.3.0
  table_calendar: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
<<<<<<< HEAD
=======
<<<<<<< HEAD

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
=======
>>>>>>> ea071398d12cde0dae3a98f32ad405996c0ef4e7
>>>>>>> 2eab770bf93ae2625c4d22ca9c9eb00e63c6e4c5
flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
<<<<<<< HEAD
=======
<<<<<<< HEAD
        # - asset: fonts/TrajanPro_Bold.ttf
        #   weight: 700
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
=======
>>>>>>> ea071398d12cde0dae3a98f32ad405996c0ef4e7
>>>>>>> 2eab770bf93ae2625c4d22ca9c9eb00e63c6e4c5
